image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - apt-get update
          - apt-get install -y zip
          - zip -r application.zip .
          - pipe: atlassian/aws-code-deploy:0.2.5
            variables:
              AWS_DEFAULT_REGION: 'us-east-1'
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              COMMAND: 'upload'
              APPLICATION_NAME: 'directcodedeploy'
              ZIP_FILE: 'application.zip'
              S3_BUCKET: 'directcodedeploy-codedeploy-deployment'
              VERSION_LABEL: 'my-app-2.0.0'
          - pipe: atlassian/aws-code-deploy:0.2.5
            variables:
              AWS_DEFAULT_REGION: 'us-east-1'
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              COMMAND: 'deploy'
              APPLICATION_NAME: 'directcodedeploy'
              DEPLOYMENT_GROUP: 'DG2'
              WAIT: 'true'
              S3_BUCKET: 'directcodedeploy-codedeploy-deployment'
              VERSION_LABEL: 'my-app-2.0.0'
              IGNORE_APPLICATION_STOP_FAILURES: 'true'
              FILE_EXISTS_BEHAVIOR: 'OVERWRITE'